name: NPM or Yarn install with caching
on: [push]
jobs:
  build-and-test: 
    runs-on: ubuntu-latest
    name: Build and test
    steps: 
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
